name: Detect Migration Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: migration-files-changed
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/db
            **/.github/workflows
      - name: List all changed files
        run: |
          echo These are the Migration Changes
          echo ${{ steps.migration-files-changed.outputs.all_changed_files }}
          LL=$(echo ${{ steps.migration-files-changed.outputs.all_changed_files }} | jq '. | length' )
          echo "::set-output name=Number_Of_Files::$LL"
      - name: Identify Branch Name
        run: echo ${{ github.event.pull_request.head.ref }}
        id: branch_name