# This is a basic workflow to help you get started with Actions

name: Files Changed

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: get-changes
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing A List of Modified / Added Files
        run: echo "${{ steps.get-changes.outputs.added_modified }}"
      
      - name: Fetch the Branch Name 
        run: echo ${{ github.event.pull_request.head.ref }}
        
      - name: Check Branch for Migration Changes
        run: |
          echo Printing All The Filenames
          for filename in ${{ steps.get-changes.outputs.added_modified }}; do
            echo filename
          done
        
      - name: Check If Branch Name is Legal
        uses: actions/github-script@v3
        if: contains(steps.get-changes.outputs.added_modified, 'db/') && contains( github.event.pull_request.head.ref, 'db_migrate' ) != 'true'
        with:
          script: |
            core.setFailed('Illegal Branch Name. Please start the branch name with db_migrate')
